pipeline:
  build:
    image: plugins/hugo
    validate: false
    url: https://yigit.run
  compress:
    image: alpine:latest
    commands:
      - apk --no-cache update
      - apk add make
      - make -C public/ -f ../Makefile
  deploy:
    image: drillster/drone-rsync
    hosts: [ "192.168.1.5" ]
    port: 3471
    target: /var/www/html/yigit.run
    source: public/*
    delete: true
    key:
      from_secret: rsync_key
    user: root
    secrets: [ rsync_key ]
