kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/hugo
  settings:
    url: https://fr1nge.xyz
    validate: false
- name: deploy
  image: drillster/drone-rsync
  hosts: [ "rsync.yigitcolakoglu.com" ]
  target: /volume/fr1nge.xyz
  source: public/*
